# Generated by Django 3.0.9 on 2021-03-07 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, null=True)),
                ('stripe_id', models.CharField(max_length=255, null=True)),
                ('card_id', models.CharField(max_length=255, null=True)),
                ('creation_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creation_dt'],
            },
        ),
    ]
