# Generated by Django 3.1.5 on 2021-02-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_lol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lol',
        ),
    ]
