# Generated by Django 3.1.5 on 2021-01-24 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swaps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Freeform',
        ),
    ]
