# Generated by Django 3.1.5 on 2021-02-07 06:00

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=255, null=True)),
                ('controller_name', models.CharField(max_length=511, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('kyc_level', models.IntegerField(null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('nric', models.IntegerField(null=True)),
                ('passport', models.IntegerField(null=True)),
                ('creation_dt', models.DateTimeField(null=True)),
                ('verification_dt', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-creation_dt'],
            },
        ),
    ]
