# Generated by Django 3.1.5 on 2021-02-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_auto_20210207_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='controller_name',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='controller_nickname',
            new_name='owner_nickname',
        ),
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='passport',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
