# Generated by Django 3.0.9 on 2021-02-24 13:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_auto_20210220_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('creation_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creation_dt'],
            },
        ),
    ]
